### ISSUE TITLE
Version 0.4.4. is broken

### ISSUE THREAD

**Issue by roman-yakobnyuk** [asprouse/serverless-webpack-plugin#25]
We found that in the version 0.4.4 imports and requires are not resolving properly on lambda deployment.

It works fine if version is reverted to 0.4.3

Error we get is:

```
Module not found: Error: Cannot resolve 'file' or 'directory' ../../lib/auth/login in /home/$PATH/_meta/_tmp/login@1468978270231
 @ ./_meta/_tmp/login@1468978270231/handler.js 12:13-44  
```

**Comment by asprouse** [comment]
Can you provide more information on your setup? NPM version? My guess is that it may be due to the changes in #23, but I need more info to reproduce.

**Comment by joostfarla** [comment]
I have the same issue after the upgrade from 0.4.3 to 0.4.4. It seems loading custom dependencies (using a relative path) breaks. For example:

``` js
const auth = require('../auth');
```

NPM version is 3.9.3 on Node version 4.3.2.

**Comment by asprouse** [comment]
I'll look into this issue and hopefully have a fix today. In the meanwhile downgrade to 0.4.3
