### ISSUE TITLE
Make this plugin's API use only one copy of webpack by default

### ISSUE THREAD

**Issue by tribou** [asprouse/serverless-webpack-plugin#4]
Last week, I hit this obscure webpack error:

```
Error: No template for dependency: TemplateArgumentDependency
```

which was resolved with the following:

https://github.com/webpack/webpack/issues/1082#issuecomment-189700673

Is there a good way to either structure the docs or redo the way `serverless-webpack-plugin` uses webpack to help prevent newcomers from using more than one copy of webpack by default?

**Comment by asprouse** [comment]
I will look into making webpack a peer dependency. This should alleviate the version mismatch issues.
