### ISSUE TITLE
node-mysql2 "undefined is not a function", "errorType": "TypeError"

### ISSUE THREAD

**Issue by thewillhuang** [asprouse/serverless-webpack-plugin#5]
hello all, i've been trying to get node-msql2 to work with lambda and i keep getting the above error, turns out, it was caused by webpack's uglifyjs plugin, disable it, and your bundle size will increase by 100%, but this error goes away. In any case, because this is not being transferred every time your client views your page, a big bundle size really doesn't matter that much.

just wanted to point that out, so you don't waste hours on it for no reason :+1:

**Comment by asprouse** [comment]
This is more of an issue with node-msql2 and uglify than with this plugin in particular. The webpack config provided in the docs is just a sample that has worked well for me in the past. One of the design goals of this plugin is to allow users to provide their own customized webpack config as opposed to providing one with opinionated defaults. Depending on what node modules and language (ES6, CoffeeScript, TypeScript, etc) it's inevitable users will have to customize the config to some degree. That said I will look into improving the documentation to make this more clear.
